FFT tests

In [ ]:
from scipy.fftpack import fft, ifft
print(fft([1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0]))
print(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j]))

print(abs(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j])))

Numpy tests

In [ ]:
import numpy as np
n = np.linspace(1.2,3)
print(len(n))
n

n = np.linspace(1.2,3, endpoint=False)
print(len(n))
n

n = np.linspace(1.2,3, num=3)
n

n = np.linspace(1.2,3, num=3, endpoint=False)
n

np.zeros(3)

Windowtests

In [ ]:
from scipy import signal
w = signal.hann(10)
print(w)
print(len(w))

w2 = signal.hann(10, False)
print(w2)
print(len(w2))

In [ ]:
w = [1,2,3]
print(w[:-1])

In [ ]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.blackman(10)
print(w)
print(len(w))

w2 = signal.blackman(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.blackmanharris(10)
print(w)
print(len(w))

w2 = signal.blackmanharris(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.flattop(10)
print(w)
print(len(w))

w2 = signal.flattop(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.nuttall(10)
print(w)
print(len(w))

w2 = signal.nuttall(10, False)
print(w2)
print(len(w2))

In [ ]:
from numpy.core.numeric import (
    absolute, asanyarray, arange, zeros, greater_equal, multiply, ones,
    asarray, where, int8, int16, int32, int64, empty, promote_types, diagonal,
    nonzero
    )

x = asarray([99,99,99])
N = len(x)
v = empty((len(x), N), dtype=promote_types(x.dtype, int))

print(v)

tmp = v[:, ::-1]

tmp[:, 1:] = x[:, None]

print(tmp)
print(x[:, None])

multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)

In [ ]:
from numpy.lib.twodim_base import vander
print(vander([2,4,8], increasing = True))
print(vander([2,4,8]))

print(vander([2,4,8], N = 2, increasing = True))
print(vander([2,4,8], N = 2))

In [ ]:
from numpy.lib.twodim_base import vander
import numpy as np
v = vander([2,4,8])
w = asarray([2,2,2])
print(v)
print(w[:, np.newaxis])
v * w[:, np.newaxis]

In [ ]:
import numpy.core.numeric as NX
import numpy as np

lhs = vander([2,4,8])
print(lhs)
scale = NX.sqrt((lhs*lhs).sum(axis=0))
print(scale)
res = lhs / scale
print(res)

# a = np.array([[1,2,3],[1,2,3],[1,2,3]])
# b = np.array([[1],[2],[3]])

# print(a/b)

In [3]:
import numpy as np

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])
# a = np.array(((
#     (12, -51,   4),
#     ( 6, 167, -68),
#     (-4,  24, -41),
# )))

q, r = np.linalg.qr(a)
print(q)
print(r)

# q:
#  [[-0.857143  0.394286  0.331429]
#  [-0.428571 -0.902857 -0.034286]
#  [ 0.285714 -0.171429  0.942857]]
# r:
#  [[ -14.  -21.   14.]
#  [   0. -175.   70.]
#  [   0.    0.  -35.]]

[[-0.06052275 -0.6022239  -0.79602975]
 [-0.24209101 -0.76482436  0.59702231]
 [-0.96836405  0.22884508 -0.09950372]]
[[-66.09084657  -8.83632198  -1.27097782]
 [  0.          -2.43298457  -1.13820318]
 [  0.           0.          -0.29851116]]


In [ ]:
import scipy.linalg as la

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])

p, l, u = la.lu(a)
print(l)
print(u)
print(p)

In [ ]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

a = np.array([[1,2,3], [4,5,6], [7,8,10]])
b = np.array([9,4,6])
x = np.linalg.solve(a, b)
print(x)

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,10]])
x = np.linalg.inv(a)
print(x)

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,10]])
x = np.matrix.transpose(a)
print(x)

In [ ]:
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
z = np.polyfit(x, y, 3)
print(z)

x = np.array([0.0, 1.0,  2.0,  3.0,  4.0,  5.0,   6.0,   7.0,   8.0,   9.0,  10.0]);
y = np.array([1.0, 6.0, 17.0, 34.0, 57.0, 86.0, 121.0, 162.0, 209.0, 262.0, 321.0]);
z = np.polyfit(x, y, 3)
print(z)

In [4]:
x = np.array([7614, 7614, 7614, 7980, 7980, 7980, 7980])
y = np.array([1, 4, 20, 25, 25, 20, 4])
z = np.polyfit(x, y, 5)
print(z)

[ 9.70248526e-19  4.88092689e-15  1.64391055e-11 -4.49364465e-08
 -1.72866393e-03 -2.43883188e+01]


/Users/polotto/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: RankWarning: Polyfit may be poorly conditioned
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
import numpy as np

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])
u, s, vh = np.linalg.svd(a, full_matrices=True)

print(u)
print(s)
print(vh)

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
u, s, vh = np.linalg.svd(a, full_matrices=True)
print()
print(u)
print(s)
print(vh)

In [ ]:
import numpy as np

y = np.array([9,8,7,6])
x = np.array([1,3,1,1])
nd = y.ndim
print(y.shape)
print(len(y.shape))

axis = -1
dx = 1

# d = dx
d = np.diff(x)
print(d)

slice1 = [slice(None)]*nd
slice2 = [slice(None)]*nd
slice1[axis] = slice(1, None)
slice2[axis] = slice(None, -1)

print(slice1)
print(slice2)

print(tuple(slice1))
print(tuple(slice2))

print(y[tuple(slice1)])
print(y[tuple(slice2)])

print(np.trapz(y, x=x))

ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
print(ret)



In [ ]:
def tupleset(t, i, value):
    l = list(t)
    l[i] = value
    return tuple(l)

y = np.array([9,8,7,6,5,4,3,2,1])
x = np.array([1,3,1,1])
axis = -1
dx = 1

N = y.shape[axis]
start = 0
stop = N - 2
step = 2

nd = len(y.shape)
if start is None:
    start = 0
step = 2
slice_all = (slice(None),)*nd
slice0 = tupleset(slice_all, axis, slice(start, stop, step))
slice1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
slice2 = tupleset(slice_all, axis, slice(start+2, stop+2, step))

print(slice_all)
print(slice0)
print(slice1)
print(slice2)

print(y[slice0])
print(y[slice1])
print(y[slice2])

def _basic_simps(y, start, stop, x, dx, axis):
    nd = len(y.shape)
    if start is None:
        start = 0
    step = 2
    slice_all = (slice(None),)*nd
    slice0 = tupleset(slice_all, axis, slice(start, stop, step))
    slice1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
    slice2 = tupleset(slice_all, axis, slice(start+2, stop+2, step))

    if x is None:  # Even spaced Simpson's rule.
        result = np.sum(dx/3.0 * (y[slice0]+4*y[slice1]+y[slice2]),
                        axis=axis)
    else:
        # Account for possibly different spacings.
        #    Simpson's rule changes a bit.
        h = np.diff(x, axis=axis)
        sl0 = tupleset(slice_all, axis, slice(start, stop, step))
        sl1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
        h0 = h[sl0]
        h1 = h[sl1]
        hsum = h0 + h1
        hprod = h0 * h1
        h0divh1 = h0 / h1
        tmp = hsum/6.0 * (y[slice0]*(2-1.0/h0divh1) +
                          y[slice1]*hsum*hsum/hprod +
                          y[slice2]*(2-h0divh1))
        result = np.sum(tmp, axis=axis)
    return result

In [ ]:
from scipy import integrate

axis = -1
dx = 1
print(integrate.simps(y))

x = np.arange(0, 10)
y = np.arange(0, 10)

N = y.shape[axis]
start = 0
stop = N - 2
step = 2
axis = -1
dx = 1

print(integrate.simps(y, x=x))
print(integrate.trapz(y, x=x))

print(_basic_simps(y, start, stop, x, dx, axis))

x = np.asarray(x)
if len(x.shape) == 1:
    shapex = [1] * nd
    shapex[axis] = x.shape[0]
    saveshape = x.shape
    returnshape = 1
    x = x.reshape(tuple(shapex))
print(x)

print(_basic_simps(y, start, stop, x, dx, axis))

print(N % 2 == 0)

In [ ]:
slice1 = (slice(None),)*nd
slice2 = (slice(None),)*nd

print(x)

print(tupleset(slice1, axis, 0))
print(tupleset(slice2, axis, 1))

print(x[tuple(tupleset(slice1, axis, 0))])
print(x[tuple(tupleset(slice1, axis, 1))])

print(tupleset(slice1, axis, -1))
print(tupleset(slice2, axis, -2))
print(x[tuple(tupleset(slice1, axis, -1))])
print(x[tuple(tupleset(slice2, axis, -2))])

x = 0.0

x += np.array([1,2,3])
print(x + 50)

In [ ]:
x = np.linspace(-2, 2, num=20)
y = x
y_int = integrate.cumtrapz(y, x, initial=0)
print(y_int)

In [ ]:
y = np.array([1, 2, 3])
print(integrate.cumtrapz(y))
print(integrate.cumtrapz(y, initial=1))

In [ ]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)

dy = np.zeros(y.shape,np.float)
print(dy)
dy[0:-1] = np.diff(y)/np.diff(x)
print(dy)
dy[-1] = (y[-1] - y[-2])/(x[-1] - x[-2])
dy

In [ ]:
import numpy as np

nyq = 1
cutoff = [0.1, 0.2, 0.3, 0.4]

cutoff = np.atleast_1d(cutoff) / float(nyq)

band = cutoff.reshape(-1, 2)
print(band)

for l, r in band:
    print(l, r)

pass_zero = False

print(cutoff.size)
print(cutoff.size & 1)

print(True ^ True)

pass_nyquist = bool(cutoff.size & 1) ^ pass_zero

print(pass_nyquist)

print([0.0] * False)

In [ ]:
import numpy as np
np.sinc([0.5 * np.pi, np.pi, (3 / 2) * np.pi, 2 * np.pi])

In [ ]:
import scipy as sp
sp.special.i0([0, 100, 0, 100])

In [ ]:
x = [1,2,3]
x[:-1]

In [103]:
from scipy import signal
window = signal.kaiser(51, beta=14)
window 

window = signal.kaiser(51, beta=14, sym=False)
window

signal.get_window(('kaiser', 4.0), 9)

signal.get_window(4.0, 9)

signal.get_window('black', 10)

array([-1.38777878e-17,  4.02128624e-02,  2.00770143e-01,  5.09787138e-01,
        8.49229857e-01,  1.00000000e+00,  8.49229857e-01,  5.09787138e-01,
        2.00770143e-01,  4.02128624e-02])

In [ ]:
import numpy as np

cutoff = np.array([0.5])
np.any(np.diff(cutoff))

In [110]:
# https://stackoverflow.com/questions/1987694/how-to-print-the-full-numpy-array-without-truncation
import sys
import numpy as np
from scipy import signal as sg
import matplotlib.pyplot as plt
np.set_printoptions(threshold=sys.maxsize)

def plotSinal(t, x):
    plt.plot(t, x)
    plt.ylabel('Amplitude')
    plt.xlabel('Tempo (s)')
    plt.xlim(0, 10)
    plt.grid(True)
    plt.show()

# generate the signals
N = 50.0
fs = 128
n = np.linspace(0, N, num= int(N*fs), endpoint=False)

f1 = 1 # 1Hz
sg1 = np.sin(n*2*np.pi*f1)

f2 = 10 # 10Hz
sg2 = np.sin(n*2*np.pi*f2)

sgF = sg1 + sg2

# print(sg1)
# print(sg2)
# print(sgF)
# print(n)

# design filter
nyq = 0.5 * fs
fc = 1
normal_fc = fc / nyq
numtaps = 30
b = sg.firwin(numtaps, [normal_fc])

# filter the signal
sgFiltered = sg.lfilter(b, [1.0], sgF)

# sgFiltered

# plotSinal(n, sg1)
# plotSinal(n, sgF)
# plotSinal(n, sgFiltered)

In [ ]:
import numpy as np

np.log10([0.1, 1, 10, 100])

In [117]:
import numpy as np

def dbfft(x, fs, win=None, ref=32768):
    """
    Calculate spectrum in dB scale
    Args:
        x: input signal
        fs: sampling frequency
        win: vector containing window samples (same length as x).
             If not provided, then rectangular window is used by default.
        ref: reference value used for dBFS scale. 32768 for int16 and 1 for float

    Returns:
        freq: frequency vector
        s_db: spectrum in dB scale
    """

    N = len(x)  # Length of input sequence

    if win is None:
        win = np.ones(N)
        print(len(win))
    if len(x) != len(win):
            raise ValueError('Signal and window must be of the same length')
    x = x * win

    # Calculate real FFT and frequency vector
    sp = np.fft.rfft(x)
#     sp = sp[:len(sp)//2]
    freq = np.arange((N / 2) + 1) / (float(N) / fs)

    # Scale the magnitude of FFT by window and factor of 2,
    # because we are using half of FFT spectrum.
    s_mag = np.abs(sp) * (2 / np.sum(win))

    # Convert to dBFS
    s_dbfs = 20 * np.log10(s_mag/ref)

    return freq, s_dbfs

# generate the signals
N = 10.0
fs = 10
n = np.linspace(0, N, num= int(N*fs), endpoint=False)

f1 = 1 # 1Hz
sg1 = np.sin(n*2*np.pi*f1)

print(len(sg1))

dbs = dbfft(sg1, fs)
print(len(dbs[0]))
print(len(dbs[1]))
print(dbs)

100
100
51
51
(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ]), array([-396.82385374, -401.33202052, -407.04917523, -415.43286071,
       -402.80353597, -399.06105916, -403.76851492, -402.76164868,
       -402.73285387, -402.06646097,  -90.3089987 , -396.29726491,
       -401.81175052, -405.28609821, -413.42907823, -397.75441859,
       -400.65583836, -403.14740317, -399.9349631 , -401.81347237,
       -400.64236041, -397.59508689, -409.42546121, -410.31589832,
       -403.98704145, -398.3382704 , -397.01763828, -415.52306087,
       -403.5856551 , -401.83539856, -392.08781713, -402.99382545,
       -396.5412601 , -405.43547178, -402.78279116, -398.2455716 ,
       -401.79845354, -406.38899573, -397.79290681, -397.6235298 ,
       -405.31839445, -402.710

In [108]:
x = np.array([1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]);
np.fft.rfft(x)

# generate the signals
N = 10.0
fs = 10
n = np.linspace(0, N, num= int(N*fs), endpoint=False)

f1 = 1 # 1Hz
x = np.sin(n*2*np.pi*f1)

X = np.fft.rfft(x)
X

array([ 2.36171372e-14+0.00000000e+00j, -9.00541287e-15+1.07904914e-14j,
        3.62254533e-15-6.31142149e-15j,  2.71761134e-15-5.45889252e-16j,
        1.15561038e-14-2.68677154e-15j, -3.55247667e-16+1.82509185e-14j,
       -8.61825328e-15-6.20019692e-15j,  9.93348561e-15+6.59183943e-15j,
        1.15990293e-14-2.92138105e-15j, -5.90169617e-15+1.14877810e-14j,
       -1.42108547e-14-5.00000000e+01j, -1.46545974e-14-2.03694215e-14j,
       -1.77089966e-16-1.32982321e-14j,  6.90135294e-15-5.64324728e-15j,
       -4.84270886e-16+3.45737917e-15j,  4.66128841e-15-2.06993876e-14j,
        1.45703920e-14+4.30284012e-15j,  1.13594668e-14+1.00462979e-15j,
        1.19369103e-14+1.14015692e-14j,  7.86242669e-15+1.07231746e-14j,
        2.46566275e-15+1.50149484e-14j, -1.88187583e-14+1.06240163e-14j,
       -5.39608870e-15-1.23392838e-15j, -4.96090167e-15-5.91412460e-16j,
        9.68393922e-15+3.66152235e-15j, -3.99340142e-15+1.94323044e-14j,
       -2.29295458e-14-2.76843378e-15j,  2.66489842